version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    allow:
      - dependency-name: letterboxdpy
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps
