target-version = "py314"
extend-exclude = ["notebooks"]

[lint]
select = ["E4", "E7", "E9", "F", "I", "BLE001", "SIM117"]

[lint.per-file-ignores]
"alembic/env.py" = ["F403"]
"alembic/versions/5f9b770770c7_initial_migration.py" = ["F401", "I001"]
"alembic/versions/d21d72f5089f_creating_tables.py" = ["I001"]
"alembic/versions/f83c598356b3_fixing_ratings_to_floats.py" = ["I001"]
"app/db/loaders/load_films.py" = ["BLE001"]
"app/db/loaders/sync_logs.py" = ["SIM117"]
"app/models/actor.py" = ["F821"]
"app/models/country.py" = ["F821"]
"app/models/director.py" = ["F821"]
"app/models/film.py" = ["F821"]
"app/models/genre.py" = ["F821"]
"app/models/language.py" = ["F821"]
"app/models/logs.py" = ["F821"]
"app/models/studio.py" = ["F821"]
"app/models/theme.py" = ["F821"]
"app/models/user.py" = ["F821"]
"tests/test_ncf_model.py" = ["E402"]
"tests/test_ncf_recommendation_service.py" = ["E402"]
"tests/test_ncf_training.py" = ["E402"]
